eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  #数据库连接配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/example?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456789

#mybatis的相关配置
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.data.dto
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true
