eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  rabbitmq:
    username: rabbitadmin
    password: 123456
    addresses: 10.221.253.155:5672
    cache:
      connection:
        #       缓存连接模式,默认一个连接,多个channel
        mode: channel
#       多个连接,多个channel
#       mode: connection
